# Generated by Django 3.0.8 on 2020-07-20 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('h', 'HTML'), ('d', 'Django'), ('p', 'Python'), ('js', 'JavaScript'), ('r', 'React')], default='h', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('live_url', models.URLField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('screen_shot', models.ImageField(blank=True, upload_to='media/post_screenshots/')),
                ('up_vote', models.IntegerField(default=0)),
                ('post_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
