# Generated by Django 3.0.8 on 2020-07-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('d', 'Django'), ('js', 'JavaScript'), ('p', 'Python'), ('h', 'HTML'), ('r', 'React')], default='h', max_length=10),
        ),
    ]
