<<<<<<< HEAD:postapp/migrations/0002_auto_20200720_2117.py
# Generated by Django 3.0.8 on 2020-07-20 21:17
=======
# Generated by Django 3.0.8 on 2020-07-21 01:59
>>>>>>> 23fbc2aeae3bfaeb9b24a6189951077973940ecd:postapp/migrations/0002_auto_20200721_0159.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
<<<<<<< HEAD:postapp/migrations/0002_auto_20200720_2117.py
            field=models.CharField(choices=[('h', 'HTML'), ('d', 'Django'), ('r', 'React'), ('js', 'JavaScript'), ('p', 'Python')], default='h', max_length=10),
=======
            field=models.CharField(choices=[('r', 'React'), ('h', 'HTML'), ('p', 'Python'), ('js', 'JavaScript'), ('d', 'Django')], default='h', max_length=10),
>>>>>>> 23fbc2aeae3bfaeb9b24a6189951077973940ecd:postapp/migrations/0002_auto_20200721_0159.py
        ),
    ]
