# Generated by Django 3.0.8 on 2020-07-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_auto_20200719_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('d', 'Django'), ('r', 'React'), ('js', 'JavaScript'), ('h', 'HTML'), ('p', 'Python')], default='h', max_length=10),
        ),
    ]
