# Generated by Django 3.0.8 on 2020-07-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_auto_20200720_2117'),
        ('postapp', '0002_auto_20200721_0159'),
    ]

    operations = [
    ]
