# Generated by Django 3.0.8 on 2020-07-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0004_auto_20200719_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('d', 'Django'), ('js', 'JavaScript'), ('r', 'React'), ('h', 'HTML'), ('p', 'Python')], default='h', max_length=10),
        ),
    ]
