# Generated by Django 3.0.8 on 2020-07-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0005_auto_20200720_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('p', 'Python'), ('js', 'JavaScript'), ('h', 'HTML'), ('d', 'Django'), ('r', 'React')], default='h', max_length=10),
        ),
    ]
