# Generated by Django 3.0.8 on 2020-07-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0006_auto_20200720_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='live_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('js', 'JavaScript'), ('h', 'HTML'), ('p', 'Python'), ('r', 'React'), ('d', 'Django')], default='h', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='repo_url',
            field=models.URLField(blank=True),
        ),
    ]
