# Generated by Django 3.0.8 on 2020-07-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0007_auto_20200720_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('js', 'JavaScript'), ('p', 'Python'), ('d', 'Django'), ('r', 'React'), ('h', 'HTML')], default='h', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='screen_shot',
            field=models.ImageField(blank=True, upload_to='media/post_screenshots'),
        ),
    ]
