# Generated by Django 3.0.8 on 2020-07-10 02:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=3)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('summary', models.TextField(max_length=1000)),
                ('school', models.CharField(max_length=75)),
                ('school_start', models.DateField()),
                ('school_end', models.DateField()),
                ('skills', models.TextField(max_length=1000)),
                ('organization', models.TextField(max_length=100)),
                ('org_city', models.CharField(max_length=50)),
                ('org_state', models.CharField(max_length=15)),
                ('job_title', models.CharField(max_length=75)),
                ('department', models.CharField(max_length=75)),
                ('job_start', models.DateField()),
                ('job_end', models.DateField()),
                ('about_list', models.TextField(max_length=100)),
                ('ref_name', models.CharField(max_length=50)),
                ('ref_job_title', models.CharField(max_length=75)),
                ('ref_organization', models.TextField(max_length=100)),
                ('ref_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('ref_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
