<<<<<<< HEAD
# Generated by Django 3.0.8 on 2020-07-10 01:55
=======
# Generated by Django 3.0.8 on 2020-07-10 02:13
>>>>>>> ac90dc9d23858638dd7c22070265aa4afe876142

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('postapp', '0002_auto_20200710_0155'),
=======
        ('postapp', '0002_auto_20200710_0213'),
>>>>>>> ac90dc9d23858638dd7c22070265aa4afe876142
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.BooleanField(default=False)),
                ('data_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postapp.Post')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
