# Generated by Django 3.0.8 on 2020-07-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='headshot',
            field=models.ImageField(blank=True, upload_to='media/headshots/'),
        ),
    ]
